Algunos cambios en la redacción de texto e imágenes en Home
pyplan/pyplan pull request #7
Opened 2022-09-01 18:21 UTC by sofiastorani

2022-09-02 12:56 UTC, jorgedouglas71 requested changes

2022-09-02 12:56 UTC, jorgedouglas71 commented on docs/home/index.rst
> +Al acceder a la dirección de internet del servidor donde se encuentra instalado `Pyplan <https://dev.pyplan.com>`_, se presenta la página de inicio para introducir las credenciales de acceso.
El servidor para acceder a Pyplan no siempre es dev.pyplan.com porque puede que Pyplan este instalado en su propio servidor.

2022-09-06 12:39 UTC, sofiastorani commented on docs/home/index.rst
> +Al acceder a la dirección de internet del servidor donde se encuentra instalado `Pyplan <https://dev.pyplan.com>`_, se presenta la página de inicio para introducir las credenciales de acceso.
Lo dejamos como estaba.

2022-09-07 12:33 UTC, jorgedouglas71 approved these changes

2022-09-07 14:05 UTC, merged